# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:


- script: mvn install
  displayName: 'mvn install'

- script: 'curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar'
  displayName: 'Download the latest Unified Agent'
 
- script: 'java -jar wss-unified-agent.jar -c wss-unified-agent.config -apiKey 21ed7db17fe54dc28faad69005a946a2a41b30fc390c4b4f891c35059ad491b0 -product AzureDevOps -project Github'
  displayName: 'Run Unified Agent Scan'